### ISSUE TITLE
Unitize::ExpressionError (Could not evaluate 'm'.)

### ISSUE THREAD

**Issue by i2chris** [pinkynrg/Unitize#1]
Hey,

I've followed the instructions in the readme and run the rake import but It won't work:

```
Loading development environment (Rails 5.2.1)
2.5.0 :001 > Unitize(12, "m")
Traceback (most recent call last):
        1: from (irb):1
Unitize::ExpressionError (Could not evaluate 'm'.)
2.5.0 :002 > Unitize::MeasurementUnit.count
   (0.5ms)  SELECT COUNT(*) FROM "measurement_units"
 => 302 

```
Have you any idea what's wrong?  Could it be that i'm using sqlite?

**Comment by pinkynrg** [comment]
Will give you feedback as soon as I can on this. I need to test it first, I don't think sqlite is the problem but I can say it with certainty only when I try.

**Comment by i2chris** [comment]
Yes, that was it.  It works fine on postgresql.  It's not suprising really.  Thanks

**Comment by pinkynrg** [comment]
Thanks for updating me on this. I will write a note on this sqlite incompatibility.
